var classquetzal_1_1demography_1_1demographic__policy_1_1mass__based =
[
    [ "neighboring_migration", "classquetzal_1_1demography_1_1demographic__policy_1_1mass__based_1_1neighboring__migration.html", "classquetzal_1_1demography_1_1demographic__policy_1_1mass__based_1_1neighboring__migration" ]
];