var structquetzal_1_1demography_1_1dispersal__kernel_1_1gaussian__mixture =
[
    [ "param_type", "structquetzal_1_1demography_1_1dispersal__kernel_1_1gaussian__mixture_1_1param__type.html", "structquetzal_1_1demography_1_1dispersal__kernel_1_1gaussian__mixture_1_1param__type" ]
];