var searchData=
[
  ['simultaneousmultiplemerger_594',['SimultaneousMultipleMerger',['../structquetzal_1_1coalescence_1_1merger__policy_1_1SimultaneousMultipleMerger.html',1,'quetzal::coalescence::merger_policy']]],
  ['single_5ffunction_5fargument_595',['single_function_argument',['../structquetzal_1_1format_1_1newick_1_1detail_1_1single__function__argument.html',1,'quetzal::format::newick::detail::single_function_argument&lt; T &gt;'],['../structquetzal_1_1format_1_1newick_1_1single__function__argument.html',1,'quetzal::format::newick::single_function_argument&lt; T &gt;']]],
  ['single_5ffunction_5fargument_3c_20std_3a_3afunction_3c_20ret_28arg_29_3e_20_3e_596',['single_function_argument&lt; std::function&lt; Ret(Arg)&gt; &gt;',['../structquetzal_1_1format_1_1newick_1_1detail_1_1single__function__argument_3_01std_1_1function_3_01Ret_07Arg_08_4_01_4.html',1,'quetzal::format::newick::detail::single_function_argument&lt; std::function&lt; Ret(Arg)&gt; &gt;'],['../structquetzal_1_1format_1_1newick_1_1single__function__argument_3_01std_1_1function_3_01Ret_07Arg_08_4_01_4.html',1,'quetzal::format::newick::single_function_argument&lt; std::function&lt; Ret(Arg)&gt; &gt;']]],
  ['single_5ffunction_5fargument_5fimpl_597',['single_function_argument_impl',['../structquetzal_1_1format_1_1newick_1_1detail_1_1single__function__argument__impl.html',1,'quetzal::format::newick::detail::single_function_argument_impl&lt; P1 &gt;'],['../structquetzal_1_1format_1_1newick_1_1single__function__argument__impl.html',1,'quetzal::format::newick::single_function_argument_impl&lt; P1 &gt;']]],
  ['spatialgeneticsample_598',['SpatialGeneticSample',['../classquetzal_1_1format_1_1genetics_1_1SpatialGeneticSample.html',1,'quetzal::format::genetics']]],
  ['spatialgeneticsample_3c_20coord_5ftype_2c_20quetzal_3a_3aformat_3a_3agenetics_3a_3adiploidindividual_20_3e_599',['SpatialGeneticSample&lt; coord_type, quetzal::format::genetics::DiploidIndividual &gt;',['../classquetzal_1_1format_1_1genetics_1_1SpatialGeneticSample.html',1,'quetzal::format::genetics']]],
  ['square_5fbracket_600',['square_bracket',['../structquetzal_1_1format_1_1newick_1_1detail_1_1square__bracket.html',1,'quetzal::format::newick::detail::square_bracket'],['../structquetzal_1_1format_1_1square__bracket.html',1,'quetzal::format::square_bracket']]],
  ['srs_601',['SRS',['../classquetzal_1_1geography_1_1gdalcpp_1_1SRS.html',1,'quetzal::geography::gdalcpp']]],
  ['standard_5fdata_602',['standard_data',['../classquetzal_1_1mutation_1_1JC69_1_1standard__data.html',1,'quetzal::mutation::JC69']]],
  ['support_603',['Support',['../classquetzal_1_1coalescence_1_1occupancy__spectrum_1_1Support.html',1,'quetzal::coalescence::occupancy_spectrum']]],
  ['symetric_5fbinop_5ft_604',['symetric_binop_t',['../structquetzal_1_1expressive_1_1symetric__binop__t.html',1,'quetzal::expressive']]]
];
