var structquetzal_1_1demography_1_1dispersal__kernel_1_1UndefinedInversePowerLaw =
[
    [ "param_type", "classquetzal_1_1demography_1_1dispersal__kernel_1_1UndefinedInversePowerLaw_1_1param__type.html", "classquetzal_1_1demography_1_1dispersal__kernel_1_1UndefinedInversePowerLaw_1_1param__type" ]
];